### ISSUE TITLE
InvalidAsn1Error: 'Expected 0x2: got 0x0'

### ISSUE THREAD

**Issue by douglaspossas** [markabrahams/node-net-snmp#6]
How to solve this issue?

{ [InvalidAsn1Error: Expected 0x2: got 0x0] name: 'InvalidAsn1Error', message: 'Expected 0x2: got 0x0' }

/var/www/courious/node_modules/net-snmp/index.js:918
var req = this.unregisterRequest (message.pdu.id);
^
TypeError: Cannot read property 'pdu' of undefined
at Session.onMsg (/var/www/courious/node_modules/net-snmp/index.js:918:43)
at Socket.EventEmitter.emit (events.js:98:17)
at UDP.onMessage (dgram.js:440:8)

This error message is displayed in an attempt to capture SNMP information from a printer. It would be wrong of LIB ASN1 or LIB net-snmp that makes use of this?

**Comment by stephenwvickers** [comment]
Can you send through a packet capture which includes the SNMP request and response?

Thanks

**Comment by douglaspossas** [comment]
How to capture this information?

**Comment by douglaspossas** [comment]
var oids = [
	"1.3.6.1.2.1.25.3.2.1.3.1"
]; //MODEL OID

var session = snmp.createSession(args.ip, "public", {
	timeout: 10000
});

session.get(oids, function (error, varbinds) {
	if ( error && !varbinds ){
		obj.erro = error;
	} else {
		for (var i = 0; i < varbinds.length; i++){
			if ( snmp.isVarbindError(varbinds[i]) ){
				console.log( 'Error attpempt capture modelo information: '+snmp.varbindError(varbinds[i]));
			} else {
				var model = (new String(varbinds[i].value)).toString();
			}
		}
	}
});

session.on('error',function(err){
	console.log('Error attempt capture model information '+args.ip+'...');
	console.log(err); //InvalidAsn1Error: 'Expected 0x2: got 0x0' - EXIT PROGRAM
});

**Comment by douglaspossas** [comment]
I had to check before the line 918 to variable message has value. In this way, I had to change the lib and the system did not stop.As it needed the system to continue even with this error, which was provisionally solved my problem:

if (message) {
...
}

**Comment by stephenwvickers** [comment]
I can look at the undefined pdu error, but that's not the original issue.

You can use a tool like Wireshark or tcpdump to capture the SNMP requests and responses, and send through the resulting capture file.

**Comment by douglaspossas** [comment]
Error in 128.100.4.105...
{ [InvalidAsn1Error: Expected 0x2: got 0x0] name: 'InvalidAsn1Error', message: 'Expected 0x2: got 0x0' }

//REQUEST -> sudo tcpdump -v -nn -ni eth0 src host 128.100.1.16 | grep 128.100.4.105
128.100.1.16.43528 > 128.100.4.105.9100: Flags [S], cksum 0x0670 (incorrect -> 0xeb0e), seq 1788886858, win 29200, options [mss 1460,sackOK,TS val 45312621 ecr 0,nop,wscale 7], length 0
128.100.1.16.43528 > 128.100.4.105.9100: Flags [.], cksum 0x0668 (incorrect -> 0x8d53), ack 3097093607, win 229, options [nop,nop,TS val 45312621 ecr 5201618], length 0
12:30:13.831813 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 128.100.4.105 tell 128.100.1.16, length 28
128.100.1.16.43528 > 128.100.4.105.9100: Flags [F.], cksum 0x0668 (incorrect -> 0x886d), seq 0, ack 1, win 229, options [nop,nop,TS val 45313874 ecr 5201618], length 0
128.100.1.16.43528 > 128.100.4.105.9100: Flags [.], cksum 0x0668 (incorrect -> 0x74da), ack 2, win 229, options [nop,nop,TS val 45313874 ecr 5206628], length 0
128.100.1.16.57265 > 128.100.4.105.161:  { SNMPv1 { GetRequest(30) R=7025966  .1.3.6.1.2.1.25.3.2.1.3.1 } } 
12:31:01.335707 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 128.100.4.105 tell 128.100.1.16, length 28

//RESPONSE -> sudo tcpdump -v -nn -ni eth0 dst host 128.100.1.16 | grep 128.100.4.105
128.100.4.105.9100 > 128.100.1.16.43528: Flags [S.], cksum 0x48d1 (correct), seq 3097093606, ack 1788886859, win 5792, options [mss 1460,sackOK,TS val 5201618 ecr 45312621,nop,wscale 2], length 0
12:30:13.832054 ARP, Ethernet (len 6), IPv4 (len 4), Reply 128.100.4.105 is-at 00:c0:ee:93:b5:b0, length 46
128.100.4.105.9100 > 128.100.1.16.43528: Flags [F.], cksum 0x7017 (correct), seq 1, ack 2, win 1448, options [nop,nop,TS val 5206628 ecr 45313874], length 0
128.100.4.105.161 > 128.100.1.16.57265:  { SNMPv1 { GetResponse(37) R=7025966  .1.3.6.1.2.1.25.3.2.1.3.1="KM-2820" } } 
12:31:01.336220 ARP, Ethernet (len 6), IPv4 (len 4), Reply 128.100.4.105 is-at 00:c0:ee:93:b5:b0, length 46

**Comment by stephenwvickers** [comment]
Hi,

I need the raw packet capture so that I can look at the bits and bytes actually being sent and received.

For tcpdump you can use the `-w <filename>` flag to write the capture to a file.

Thanks

Steve

**Comment by douglaspossas** [comment]
Error on request for 128.100.4.65

[request.txt](https://github.com/stephenwvickers/node-net-snmp/files/99460/request.txt)
[response.txt](https://github.com/stephenwvickers/node-net-snmp/files/99458/response.txt)

**Comment by atatdotdot** [comment]
I am also seeing a similar error; I'm not sure if it's identical or not:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
InvalidAsn1Error: Expected 0x2: got 0x0
    at module.exports.newInvalidAsn1Error (/home/meshmgr/snmp/node_modules/net-snmp/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader._readTag (/home/meshmgr/snmp/node_modules/net-snmp/node_modules/asn1/lib/ber/reader.js:221:11)
    at Reader.readInt (/home/meshmgr/snmp/node_modules/net-snmp/node_modules/asn1/lib/ber/reader.js:137:15)
    at new ResponseMessage (/home/meshmgr/snmp/node_modules/net-snmp/index.js:541:24)
    at Session.onMsg (/home/meshmgr/snmp/node_modules/net-snmp/index.js:913:17)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```

Unfortunately this only happens occasionally, usually after about three days of operation, so a packet capture would be massive. Is there any other info I can supply to help diagnose this crash?

**Comment by douglaspossas** [comment]
Exactly. This happens occasionally. In my case, specifically on a single client. What about the time, this is already the first time I try to trigger an SNMP command block. This client where the error occurs, I have about 60 networked printers. but on a much larger customer, with 1,200 printers, the error does not occur.

**Comment by atatdotdot** [comment]
I have started a tcpdump with a circular buffer and set it to stop when my nodejs process dies, so hopefully I'll have a capture file for you in the next few days.

**Comment by stephenwvickers** [comment]
Looking at the asn1 code, it would seem based on the error that something in the response packet is unexpected.

This is odd, a packet capture would really help so if you can get that I would appreciate it.

**Comment by stephenwvickers** [comment]
The message parsing issue has been addressed by issue:

https://github.com/stephenwvickers/node-net-snmp/issues/8

**Comment by stephenwvickers** [comment]
If you would like to continue investigating this issue please provide the packet capture and I will continue to look into it.

**Comment by atatdotdot** [comment]
@stephenwvickers, unfortunately my software hasn't crashed in the last couple of weeks since I put the logging in place! Typical. I'll definitely let you have the capture as soon as it falls over.

**Comment by atatdotdot** [comment]
@stephenwvickers, my software has eventually crashed – woohoo! ;-)

I've attached the final packet capture, and here is the error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
InvalidAsn1Error: encoding too long
    at module.exports.newInvalidAsn1Error (/home/meshmgr/snmp/node_modules/net-snmp/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader.readLength (/home/meshmgr/snmp/node_modules/net-snmp/node_modules/asn1/lib/ber/reader.js:94:13)
    at Reader.readSequence (/home/meshmgr/snmp/node_modules/net-snmp/node_modules/asn1/lib/ber/reader.js:127:16)
    at new GetResponsePdu (/home/meshmgr/snmp/node_modules/net-snmp/index.js:431:9)
    at new ResponseMessage (/home/meshmgr/snmp/node_modules/net-snmp/index.js:547:14)
    at Session.onMsg (/home/meshmgr/snmp/node_modules/net-snmp/index.js:913:17)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```

I've just noticed that this is actually a different error from last time ("encoding too long" vs "Expected 0x2: got 0x0"). I'll run the test again and see if it give the "Expected..." one again.
[net-snmp.pcap.5.txt](https://github.com/stephenwvickers/node-net-snmp/files/140397/net-snmp.pcap.5.txt)

**Comment by atatdotdot** [comment]
This "InvalidAsn1Error: encoding too long" appears to be happening repeatably, and within a few seconds of running the software. As a consequence, here is a much shorter packet capture from the latest crash.
[net-snmp.pcap.0.txt](https://github.com/stephenwvickers/node-net-snmp/files/140562/net-snmp.pcap.0.txt)

**Comment by sebashmh** [comment]
Can anyone tell me exactly how to solve this? I'm experiencing the same issue with node-net-snmp

**Comment by stephenwvickers** [comment]
@sebashmh a packet capture would help me investigate further. Thanks.

**Comment by sebashmh** [comment]
@stephenwvickers thanks for the answer, can you please explain what should I do to capture that packet ?

**Comment by stephenwvickers** [comment]
@sebashmh I just realised that @atatdotdot provided a PCAP already, I will take a look at that, so no need to provide one as of yet.  I will look into this over the coming week.

**Comment by sebashmh** [comment]
@stephenwvickers Thanks, were you able to look at the packet captured by @atatdotdot ? Looking forward to hearing any input about this error.

**Comment by markabrahams** [comment]
@sebashmh - I fixed one class of ASN decode error when I was implementing another net-snmp feature recently.  Fuelled by nothing more than speculation, there's a chance that this may have fixed your problem as well.  As something to try, you could install the latest master from my fork with this in your package.json:
"net-snmp": "https://github.com/markabrahams/node-net-snmp.git"

If that works, it would be easy to extract a small PR with just that fix in it.

**Comment by markabrahams** [comment]
@sebashmh - an update on this.  The fix code I mentioned for this has now been released in the latest NPM (v 2.1.0), so you can install this from the main NPM repository now as well.

**Comment by sebashmh** [comment]
@markabrahams thanks so much! I will test it and let you know if the problem is solved.

**Comment by sebashmh** [comment]
I just had the opportunity to check again, I updated to the last version and the problem still happens. Any ideas on how to fix this ?

**Comment by Osmosis311** [comment]
I'm also getting the encoding too long error.  Any ideas?

**Comment by markabrahams** [comment]
It appears that the original error reported: "InvalidAsn1Error: Expected 0x2: got 0x0" was resolved in 2016 by this ASN fix:
https://github.com/markabrahams/node-net-snmp/issues/8

The current problem is the "InvalidAsn1Error: encoding too long" error.

@Osmosis311 , @sebashmh , @atatdotdot - can one of you please open a new issue with a minimal code reproduction and packet captures according to CONTRIBUTING.md guidelines please?  This will remove the confusion that I initially - and possibly others - had in having two different problems reported in a single Github issue.

Meanwhile I will close this issue again, as I believe the issue as reported ("InvalidAsn1Error: Expected 0x2: got 0x0") was resolved four years ago.

**Comment by Osmosis311** [comment]
Will definitely try.

FWIW I was able to solve it by commenting out this line in reader.js:

if (lenB > 4)
//throw InvalidAsn1Error('encoding too long');
